version: '3'
services:
  python-app:
      image: python:3.10
      volumes:
        - ./:/app
      working_dir: /app
      depends_on:
        - db
      command: bash -c "pip install psycopg2; python3 ./data-upload.py"
      
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    

  