version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    expose:
      - 5432S
    
# python-app:
#       image: python:3.10
#       volumes:
#         - ./:/app
#       working_dir: /app
#       depends_on:
#         - db
#       command: bash -c "pip install psycopg2; python3 ./data-upload.py"
  